/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logan_dev_ndksampleapp_NdkSampleApp */

#ifndef _Included_com_logan_dev_ndksampleapp_NdkSampleApp
#define _Included_com_logan_dev_ndksampleapp_NdkSampleApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logan_dev_ndksampleapp_NdkSampleApp
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_logan_dev_ndksampleapp_NdkSampleApp_getString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
